services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: personal-podcast-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./src/storage:/var/www/html/storage
    networks:
      - podcast-network

  webserver:
    image: nginx:alpine
    container_name: podcast-feed-webserver
    restart: unless-stopped
    networks:
      - traefik_web
      - podcast-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.podcast.rule=Host(`podkeep.app`)"
      - "traefik.http.routers.podcast.entrypoints=websecure"
      - "traefik.http.routers.podcast.tls.certresolver=letsencrypt"
      - "traefik.http.routers.podcast.tls.domains[0].main=podkeep.app"
      - "traefik.http.services.podcast.loadbalancer.server.port=80"
      - "traefik.http.routers.podcast-http.rule=Host(`podkeep.app`)"
      - "traefik.http.routers.podcast-http.entrypoints=web"
      - "traefik.http.routers.podcast-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  traefik_web:
    external: true
  podcast-network:
    driver: bridge
